import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Layouts/Providers";
import { handleGetUser } from "@/lib/server/auth";
import { MainLayout } from "@/components/Layouts/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  // return (
  //   <html lang="en">
  //     <body
  //       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //     >
  //       {children}
  //     </body>
  //   </html>
  // );

  const user = await handleGetUser();
  return (
		<html lang="pt-br" suppressHydrationWarning>
			<body >
				<Providers>
					<MainLayout user={user}>
						
						{children}
						
					</MainLayout>
					
				</Providers>
				
			</body>
		</html>
	);


}
